### ISSUE TITLE
Time Entry App 

### ISSUE THREAD

**Issue by LylyG** [LylyG/time_entries#1]
### Phase One
- [x] Anyone can list/create/edit/delete developers.
- [x] Developers must have unique email addresses.
- [ ] Anyone can create a time entry for any developer.
- [x] The time entry form should include a dropdown for selecting the developer by name, not by id.
- [x] Time entries must have a duration, a developer, and a date.
- [x] The developer index page should have a link to the time entry creation page, and vice-versa.
- [ ] Submitting a new time entry should redirect somewhere sensible.
- [x] The application should have a root route.
### Phase Two
- [ ] Developers can log in.
- [ ] Developers can log out from any page.
- [ ] Anyone who tries to access any page without logging in is redirected to the login page.
- [ ] The application should have a root route which is NOT the login page.
### Phase Three
- [ ] Developers can only create time entries for themselves.
- [ ] Developers can see a list of just their own time entries.
- [ ] Developers can edit/delete just their own time entries.
### Phase Four
- [ ] Developers can list/create/edit/delete projects.
- [ ] Projects must have a maximum number of allowed hours.
- [ ] When time entries are created or updated, they must have a project associated with each one.  
- [ ] The time entry form should include a dropdown for selecting the project by name, not by id.
- [ ] There must be a project list page which:
- [ ] Includes a total number of hours worked on each project.
- [ ] Shows the project in red if the total number of hours on the project exceeds the number of hours allowed.
### Phase Five
- [ ] No one can delete a developer once that developer has made a time entry.
- [ ] No one can delete a project once that project has a time entry on it.
- [ ] Modify the developer list page to:
- [ ] Show the developer in red if he or she has worked more than 40 hours in the current calendar week.
### Bonus Phase
- [ ] Allow developers to create a time entry by choosing to start work at one point in time, then to end work by coming back to the application later and hitting a simple "End Current Task" button.
- [ ] Work in progress should not be counted towards the total for projects or developers.  It should count as soon as the "End Current Task" button is hit.
- [ ] The "End Current Task" button should be present on every page of the application.  Near this button, you should also see the project and start time of the current work in progress.
